name: auto_local
description: A command-line tool to generate localizations for your app automatically.
version: 2.0.0
repository: https://github.com/abom-me/auto_local
executables:
  auto_local: auto_local
environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.5.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.0
  dart_widget: ^1.0.0
  encrypt: ^5.0.3
  http: ^1.2.2
  pointycastle: ^3.9.1
  pub_updater: ^0.4.0
  tint: ^2.0.1
  watcher: ^1.1.0
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
