import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:auto_local/settings.dart';
import 'package:path/path.dart' as path;

class AutoIcon  extends Command{
Settings settings = Settings();
  @override
  // TODO: implement description
  String get description => "Generate language file and listen for any changes in icons/path/<svg files>";

  @override
  // TODO: implement name
  String get name => "icons";
  final String directoryPath = 'assets/icons/';
String className="AutoIcons";
  @override
  void run() {
    final directory = Directory(directoryPath);

    if (directory.existsSync()) {
      _generateLocalizationClasses();
      _watchDirectory(directory);
    } else {
      print('Directory not found: $directoryPath');
    }
  }

  void _watchDirectory(Directory directory) {
    directory.watch(events: FileSystemEvent.create).listen((event) {
      if (event is FileSystemCreateEvent && event.path.endsWith('.svg')) {
        _generateLocalizationClasses();
      }
    });
  }

  void _generateLocalizationClasses() {
    final directory = Directory(directoryPath);

    if (directory.existsSync()) {
      final files = directory.listSync().whereType<File>().toList();
      List<String> fileNames = [];
if(files.isEmpty){
  print('Your directory is empty. Please add some SVG files.');
  return;
}
Map<String, String> data = loadCredentials()??{};
if(data['icons']!=null){
  className = data['icons']!;

}else{
  stdout.write('✏️ Enter your class name: ');
  className = stdin.readLineSync()!.replaceAll(" ", "");
  settings.createFile({
    "icons":className,
  });
}
      for (final file in files) {
        if (file.path.endsWith('.svg')) {
          String fileName = path.basenameWithoutExtension(file.path);
          fileNames.add(fileName);
        }
      }

      _updateDartClass(fileNames);
    } else {
      print('Directory not found: $directoryPath');
    }
  }

  void _updateDartClass(List<String> names) {
    final generatedCode = _generateClassCode(names);
    Directory("lib/auto_local").create(recursive: true).then((Directory directory) {
      File('${directory.path}/icons.dart').writeAsStringSync(generatedCode);
      print("""
|-----------------------Done 👀----------------------------|
-> 🥳 Your file is created in ${directory.path}/icons.dart 🥳 <-
""");
    });
  }

  String _generateClassCode(List<String> names) {
    final StringBuffer classMethods = StringBuffer();
    int count = names.length;
    classMethods.writeln('enum ${className.replaceFirst(className[0], className[0].toUpperCase())}s {');
    names.forEach((element) {
      // Remove "-" and convert to CamelCase
      List<String> splitElement = element.replaceAll(".", "").split("-");
      String iconName = splitElement.map((e) => splitElement.indexOf(e) == 0 ? e : e[0].toUpperCase() + e.substring(1)).join();
      classMethods.write("$iconName('$element')");
      if (--count > 0) {
        classMethods.writeln(',');
      } else {
        classMethods.writeln(';');
      }
    });

    classMethods.writeln(''' 
  const ${className.replaceFirst(className[0], className[0].toUpperCase())}s(this.key);
  final String key;
 }\n''');

    return '''
  // This file is generated by Auto Local. Do not edit anything.
  // you have to add flutter_svg package to your pubspec.yaml 
  // you can add it by running this command in your terminal
  // ``` flutter pub add flutter_svg ```
  import 'package:flutter/material.dart';
  import 'package:flutter_svg/flutter_svg.dart';

  class ${className.replaceFirst(className[0], className[0].toUpperCase())} {
           static Widget show({required ${className.replaceFirst(className[0], className[0].toUpperCase())}s icon,Color?color,double?size}) {
      return SvgPicture.asset(
        "assets/icons/\${icon.key}.svg",
        color: color??Colors.black,
        fit: BoxFit.cover,
        clipBehavior: Clip.none,
        width:size?? 24,
        height: size??24,
      
        // Customize your SVG rendering options here if needed
      );
    }
  }
  
  $classMethods
  ''';
  }




  Map<String, String>? loadCredentials() {
    try {
      final file = File('auto_local.json');
      if (file.existsSync()) {
        final contents = file.readAsStringSync();
        final Map<String, dynamic> decodedData = json.decode(contents);

        // Cast to the expected type
        final Map<String, String> credentials = Map.castFrom(decodedData);
        return credentials;
      }
    } catch (error) {
      print('Error loading auto_local.json : $error');
    }
    return null;
  }

}
