// import 'dart:convert';
// import 'dart:io';
// import 'package:auto_local/print_color.dart';
// import 'package:supabase/supabase.dart';
// import 'package:watcher/watcher.dart';
// import 'dart:convert';
// import 'dart:io';
// import 'package:http/http.dart' as http;
// class AutoLocal{
// AutoLocalTool autoLocalt = AutoLocalTool();
//   final supabaseClient = SupabaseClient(
//     'http://localhost:8000',
//     'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE',
//   );
//   Print pen = Print();
//
//   run(){
//     pen.green("|------------------👋 Starting Auto Local Tool 👋----------------------------|");
//     pen.green("|                   This Tool Built by Github: abom-me                                 |");
// pen.yellow("""
//   This tool is used to generate a dart class from a JSON file.
//   the json file path should be in assets/lang/ directory.
//   because this tool is depend on flutter_locales2 package.
//   """);
//     final String directoryPath = 'assets/lang/';
//     final directory = Directory(directoryPath);
//
//     if (directory.existsSync()) {
//       _generateLocalizationClasses(); // Initial generation
//
//       // Watch for changes in the directory
//       final watcher = DirectoryWatcher(directoryPath);
//       watcher.events.listen((event) {
//         if (event.type == ChangeType.MODIFY) {
//
//           _updateDartClass(event.path);
//         }
//       });
//
//       pen.magenta("|------------------Waiting new data in $directoryPath---------------------|");
//
//       // // Keep the process running
//       // stdin.readLineSync();
//     } else {
//       pen.red('Directory not found: $directoryPath');
//     }
//   }
//
//   void _generateLocalizationClasses() {
//
//
//     final String directoryPath = 'assets/lang/';
//
//     final directory = Directory(directoryPath);
//     if (directory.existsSync()) {
//       final files = directory.listSync().whereType<File>().toList();
//       for (final file in files) {
//         if (file.path.endsWith('.json')) {
//
//         }
//       }
//       _updateDartClass(files[0].path);
//     } else {
//       print('Directory not found: $directoryPath');
//     }
//   }
//
//   void _updateDartClass(String jsonPath) {
//     final jsonString = File(jsonPath).readAsStringSync();
//     final Map<String, dynamic> jsonData = json.decode(jsonString);
//
//     final generatedCode = _generateClassCode(jsonData);
//     Directory("lib/auto_local").create(recursive: true).then((Directory directory) {
//
//       File('${directory.path}/lang.dart')
//           .writeAsStringSync(generatedCode);
//       print("""
// |-----------------------Done 👀----------------------------|
// -> 🥳 Your file is created in ${directory.path}/lang.dart 🥳 <-
// """);
//
//
//
//     });
//
//
//   }
//
//   String _generateClassCode( Map<String, dynamic> jsonData) {
//     final StringBuffer classMethods = StringBuffer();
//     classMethods.writeln('  enum LangKey{');
//
//     int count = jsonData.length;
//     jsonData.forEach((key, value) {
//       if (value is String) {
//         String formattedKey = key.replaceAllMapped(RegExp('_(\\w)'), (match) {
//           return match.group(1)!.toUpperCase();
//         });
//
//         classMethods.write("$formattedKey('$key')");
//         if (--count > 0) {
//           classMethods.writeln(',');
//         } else {
//           classMethods.writeln(';');
//         }
//       }
//       // Add other types handling if necessary (e.g., nested maps, lists, etc.)
//     });
//
//     classMethods.writeln('''
//   const LangKey(this.key);
//   final String key;
//  }\n''');
//
//     return '''
//   // This file is generated by Auto Local. Do not edit any things.
//   import 'package:flutter/material.dart';
// import 'package:flutter_locales2/flutter_locales2.dart';
//   class Lang {
//
//     static String get(BuildContext context,{required LangKey key}) {
//     return Locales.string(context, key.key) ?? '';
//   }
//   }
//     $classMethods
//
//   ''';
//   }
//
//
//
//
//   getText() async {
//    try{
//     await supabaseClient.from("text").select().then((value) => {
//
//       autoLocalt.main(value)
//
//     });
//
//    }catch(e){
//      print(e);
//    }
//    exit(0);
//   }
//
//
// }
//
//
// class AutoLocalTool {
//
// Print pen = Print();
//
//   void main( List<Map<String, dynamic>> dataList) {
// pen.yellow("Getting the strings ....");
//
//     for (int i = 1; i < dataList.length; i++) {
//       Map<String, dynamic> data = dataList[i];
//
//       // Specify the directory path
//       String directoryPath = 'assets/lang';
//
//       // Create the directory if it doesn't exist
//       Directory(directoryPath).createSync(recursive: true);
//
//       // Iterate through languages and append new 'langs' data
//       data['langs'].forEach((lang, value) {
//         // Read existing data from assets/lang/{lang}.json
//         // add \n to the end of the string to make it more readable
//
//         Map<String, dynamic> existingData = readExistingJson('$directoryPath/$lang.json');
//
//
//         // Add new 'langs' data to existing data
//         existingData[data['key']] = value;
//
//         // Save updated JSON data to assets/lang/{lang}.json
//         saveJsonToFile('$directoryPath/$lang.json', jsonEncode(existingData));
//
//         // print('Updated JSON data has been saved to $directoryPath/$lang.json');
//       });
//
//     }
//     pen.green("Your strings is downloaded from the server");
//     exit(0);
//   }
//
//   Map<String, dynamic> readExistingJson(String filePath) {
//     try {
//       File file = File(filePath);
//       if (file.existsSync()) {
//         String jsonData = file.readAsStringSync();
//
//         return jsonDecode(jsonData);
//
//       } else {
//         return {};
//       }
//     } catch (e) {
//       return {};
//     }
//   }
//
//   void saveJsonToFile(String filePath, String jsonData) {
//     jsonData = jsonData.replaceAll('","', '",\n"').replaceAll('{', '{\n').replaceAll('}', '\n}');
//
//     File(filePath).writeAsStringSync(jsonData);
//   }
// }