import 'dart:convert';
import 'dart:io';
import 'dart:mirrors';
import 'dart:typed_data';

import 'package:auto_local/print_color.dart';
import 'package:crypto/crypto.dart';
import 'package:dart_jsonwebtoken/dart_jsonwebtoken.dart';
import 'package:encrypt/encrypt.dart';

class Settings{
  final Print pen = Print();


  void createFile(Map<String, dynamic> data) {
    final file = File('auto_local.json');
    final encoder = JsonEncoder.withIndent('  ');

    if (file.existsSync()) {
      String contents = file.readAsStringSync();
      Map<String, dynamic> existingData = json.decode(contents).cast<String, dynamic>();
      data.forEach((key, value) {
        existingData[key] = value;
      });
      file.writeAsStringSync(encoder.convert(existingData));
    } else {
      file.writeAsStringSync(encoder.convert(data));
    }
    checkDotIgnores();
  }


  Map<String, dynamic>? loadFile() {
    try {
      final file = File('auto_local.json');
      if (file.existsSync()) {
        final contents = file.readAsStringSync();
        final Map<String, dynamic> decodedData = json.decode(contents);

        // Cast to the expected type
        final Map<String, dynamic> credentials = Map.castFrom(decodedData);
        return credentials;
      }
    } catch (error) {
      print('Error loading path.json : $error');
    }
    return null;
  }

   Map<String,dynamic>createJwt(String apiKey){
    String mainData = DateTime.now().toString();
    String secretKey = secretKeyMaker(mainData).substring(0, 16);
     final encrypter = Encrypter(AES(Key.fromUtf8(secretKey),mode: AESMode.ctr, padding: null));
    final iv = IV.fromUtf8(secretKey);
String encryptKey = encrypter.encrypt(apiKey, iv: iv).base64;
     String secret = encrypter.encrypt("${mainData}_${mainData}", iv: iv).base64;

    final main = JWT(
      {
        'apiKey': encryptKey,
        "createdAt": mainData,
        "message": "Here is encrypted GPT API key, generated by Auto Local Tool, you can use it to generate your language file. it's valid for 30 days.",

 },
    );
  final mainToken=  main.sign(SecretKey(secret), expiresIn: Duration(days: 30));
      return {'api':mainToken,'secret':secret};
   }

  Map<String,dynamic> checkToken() {


    Map<String, dynamic>? data = loadFile();
    if (data?['gpt_key'] == null || data?['gpt_key'] == '' || data?['secret_key'] == '' || data?['secret_key'] == null) {
      print('No API Key found, please add your API Key using --adg flag');
      return{};
    } else {
     try{
       String token = data!['gpt_key']!;
       String secretKey = data['secret_key']!;
       final jwt = JWT.verify(token, SecretKey(secretKey));

       Map<String, dynamic> refreshData = jwt.payload;
       String secret = secretKeyMaker(refreshData['createdAt']).substring(0, 16);
       final iv = IV.fromUtf8(secret);
       final decrypter = Encrypter(AES(Key.fromUtf8(secret), mode: AESMode.ctr, padding: null));
       final decrypted = decrypter.decrypt(Encrypted.fromBase64(refreshData['apiKey']), iv: iv);

       return {
         "status": true,
         "apiKey": decrypted,
       };

     }catch(e){
       print('Error: $e');
       return{"status":false};
     }
    }
  }



  String cleanMainData(String data) {
    return data.replaceAll(" ", "").replaceAll(":", "").replaceAll(".", "");
  }

String secretKeyMaker(String data) {
  return base64Encode(Uint8List.fromList(sha256
      .convert(utf8.encode(cleanMainData(data)))
      .bytes
      .sublist(0, 32)));
}

checkDotIgnores() {
  final file = File('.gitignore');
  if (!file.existsSync()) {
    file.writeAsStringSync('auto_local.json');
  } else {
    final contents = file.readAsStringSync();
    if (!contents.contains('auto_local.json')) {
      file.writeAsStringSync('$contents\nauto_local.json');
    }
  }
}

  void createFileWithContent(String path, String content) {
    final file = File(path);
    file.writeAsStringSync(content);
}


  //
  // Future<LibraryMirror> loadLibrary(String path) async {
  //   Directory current = Directory.current;
  //   print('Current Directory: $current');
  //   // print('Current Directory: $current');
  //   var uri = File("${current.path}/$path").uri;
  //   print('URI: $uri');
  //   var mirrorSystem = currentMirrorSystem();
  //   return await mirrorSystem.isolate.loadUri(uri);
  // }
  //
  // Future<void> invokeMethod(LibraryMirror library, String methodName, List<dynamic> args) async {
  //   var function = library.declarations[Symbol(methodName)] as MethodMirror;
  //   if (function == null) {
  //     print('Method not found: $methodName');
  //     exit(1);
  //   }
  //   var instanceMirror = library.getField(function.simpleName);
  //   await instanceMirror.invoke(function.simpleName, args);
  // }
}